-- Edge-only analytics ingestion, admin reporting, and privacy retention.

create extension if not exists pg_cron;

alter table private.gateway_config enable row level security;
revoke all on table private.gateway_config from public, anon, authenticated;

-- Legacy gateway functions must never be callable directly from a browser.
revoke execute on function public.gateway_rate_limit(text, text, text) from public, anon, authenticated;
revoke execute on function public.gateway_record_auth_event(text, uuid, text, text, boolean, text, text, text, text, text, numeric, numeric, text, text, text, text, text, text, text) from public, anon, authenticated;
revoke execute on function public.gateway_resolve_identifier(text, text) from public, anon, authenticated;
revoke execute on function public.gateway_set_registration_geo(text, uuid, text, text, text, text) from public, anon, authenticated;
revoke execute on function public.gateway_admin_dashboard(text) from public, anon, authenticated;
revoke execute on function public.gateway_admin_users(text, text) from public, anon, authenticated;
revoke execute on function public.gateway_admin_logins(text, integer) from public, anon, authenticated;
revoke execute on function public.gateway_admin_security(text, integer) from public, anon, authenticated;
revoke execute on function public.gateway_admin_update_user(text, uuid, text, text) from public, anon, authenticated;

create table if not exists public.edge_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique,
  visitor_id uuid not null,
  session_id uuid not null,
  event_name varchar(48) not null check (event_name ~ '^[a-z][a-z0-9_]{1,47}$'),
  path varchar(256) not null check (path like '/%' and length(path) <= 256),
  referrer_host varchar(253),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object' and pg_column_size(metadata) <= 2048),
  ip_hash varchar(64) check (ip_hash is null or ip_hash ~ '^[0-9a-f]{64}$'),
  country_code varchar(2) check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  region varchar(96),
  city varchar(96),
  timezone varchar(64),
  latitude_coarse numeric(4,1) check (latitude_coarse between -90 and 90),
  longitude_coarse numeric(4,1) check (longitude_coarse between -180 and 180),
  asn integer check (asn is null or asn > 0),
  colo varchar(3) check (colo is null or colo ~ '^[A-Z0-9]{3}$'),
  device_type varchar(16) not null default 'unknown' check (device_type in ('desktop','mobile','tablet','bot','unknown')),
  browser varchar(24) not null default 'unknown',
  os varchar(24) not null default 'unknown',
  suspected_bot boolean not null default false,
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  check (occurred_at between received_at - interval '24 hours' and received_at + interval '5 minutes')
);

alter table public.edge_events enable row level security;
revoke all on table public.edge_events from public, anon, authenticated;
grant select on table public.edge_events to authenticated;

drop policy if exists edge_events_admin_read on public.edge_events;
create policy edge_events_admin_read on public.edge_events
for select to authenticated
using ((select private.is_admin((select auth.uid()))));

create index if not exists edge_events_occurred_at_idx on public.edge_events (occurred_at desc);
create index if not exists edge_events_path_idx on public.edge_events (path, occurred_at desc);
create index if not exists edge_events_name_idx on public.edge_events (event_name, occurred_at desc);
create index if not exists edge_events_geo_idx on public.edge_events (country_code, region, city, occurred_at desc);
create index if not exists edge_events_ip_hash_idx on public.edge_events (ip_hash, occurred_at desc) where ip_hash is not null;

insert into public.edge_events (
  request_id, visitor_id, session_id, event_name, path, referrer_host,
  metadata, occurred_at, received_at
)
select gen_random_uuid(), visitor_id, session_id, event_name, path,
       nullif(referrer_host, ''), metadata, occurred_at, occurred_at
from public.site_events
on conflict do nothing;

drop policy if exists "Public can submit anonymous site events" on public.site_events;
revoke all on table public.site_events from anon, authenticated;

create table if not exists public.guestbook_submission_log (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique,
  message_id uuid not null references public.guestbook_messages(id) on delete cascade,
  ip_hash varchar(64) not null check (ip_hash ~ '^[0-9a-f]{64}$'),
  country_code varchar(2) check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  created_at timestamptz not null default now()
);

alter table public.guestbook_submission_log enable row level security;
revoke all on table public.guestbook_submission_log from public, anon, authenticated;
grant select on table public.guestbook_submission_log to authenticated;

drop policy if exists guestbook_submission_log_admin_read on public.guestbook_submission_log;
create policy guestbook_submission_log_admin_read on public.guestbook_submission_log
for select to authenticated
using ((select private.is_admin((select auth.uid()))));

create index if not exists guestbook_submission_log_ip_idx
on public.guestbook_submission_log (ip_hash, created_at desc);

create or replace function public.edge_submit_guestbook(
  p_request_id uuid,
  p_visitor_id uuid,
  p_display_name text,
  p_channel text,
  p_message text,
  p_ip_hash text,
  p_country_code text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_message_id uuid;
begin
  if p_display_name is null or length(btrim(p_display_name)) not between 1 and 40 then
    raise exception using errcode = '22023', message = 'invalid display name';
  end if;
  if p_message is null or length(btrim(p_message)) not between 2 and 500 then
    raise exception using errcode = '22023', message = 'invalid message';
  end if;
  if p_channel not in ('问候', '回声', '灵感', '足迹') then
    raise exception using errcode = '22023', message = 'invalid channel';
  end if;
  if p_ip_hash is null or p_ip_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = '22023', message = 'invalid request fingerprint';
  end if;
  if exists (
    select 1 from public.guestbook_submission_log
    where ip_hash = p_ip_hash and created_at > now() - interval '90 seconds'
  ) then
    raise exception using errcode = 'P0001', message = 'cooldown';
  end if;

  select message_id into v_message_id
  from public.guestbook_submission_log where request_id = p_request_id;
  if v_message_id is not null then return v_message_id; end if;

  insert into public.guestbook_messages(visitor_id, display_name, channel, message, status, likes)
  values (p_visitor_id, btrim(p_display_name), p_channel, btrim(p_message), 'pending', 0)
  returning id into v_message_id;

  insert into public.guestbook_submission_log(request_id, message_id, ip_hash, country_code)
  values (p_request_id, v_message_id, p_ip_hash, nullif(upper(p_country_code), ''));
  return v_message_id;
end;
$$;

revoke execute on function public.edge_submit_guestbook(uuid, uuid, text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.edge_submit_guestbook(uuid, uuid, text, text, text, text, text) to service_role;

drop policy if exists "Public can submit pending guestbook messages" on public.guestbook_messages;
revoke insert, update, delete on table public.guestbook_messages from anon, authenticated;
revoke select on table public.guestbook_messages from anon, authenticated;
grant select (id, display_name, channel, message, likes, created_at, approved_at) on public.guestbook_messages to anon, authenticated;
grant select on table public.guestbook_messages to authenticated;
grant update (status, approved_at) on public.guestbook_messages to authenticated;

drop policy if exists guestbook_admin_read on public.guestbook_messages;
create policy guestbook_admin_read on public.guestbook_messages
for select to authenticated
using ((select private.is_admin((select auth.uid()))));

drop policy if exists guestbook_admin_update on public.guestbook_messages;
create policy guestbook_admin_update on public.guestbook_messages
for update to authenticated
using ((select private.is_admin((select auth.uid()))))
with check (
  (select private.is_admin((select auth.uid())))
  and status in ('pending', 'approved', 'hidden')
);

create or replace function private.audit_guestbook_moderation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status is distinct from new.status then
    insert into public.admin_audit_logs(admin_user_id, action, target_type, target_id, metadata)
    values (
      auth.uid(), 'GUESTBOOK_MODERATED', 'guestbook_message', new.id::text,
      jsonb_build_object('from', old.status, 'to', new.status)
    );
  end if;
  return new;
end;
$$;
revoke execute on function private.audit_guestbook_moderation() from public, anon, authenticated;

drop trigger if exists audit_guestbook_moderation on public.guestbook_messages;
create trigger audit_guestbook_moderation
after update of status on public.guestbook_messages
for each row execute function private.audit_guestbook_moderation();

create table if not exists public.analytics_rollups (
  day date not null,
  event_name varchar(48) not null,
  event_label varchar(64) not null default '',
  path varchar(256) not null default '',
  referrer_host varchar(253) not null default '',
  country_code varchar(2) not null default '',
  region varchar(96) not null default '',
  city varchar(96) not null default '',
  device_type varchar(16) not null default '',
  browser varchar(24) not null default '',
  os varchar(24) not null default '',
  event_count bigint not null check (event_count >= 0),
  visitor_count bigint not null check (visitor_count >= 0),
  session_count bigint not null check (session_count >= 0),
  suspected_bot_count bigint not null check (suspected_bot_count >= 0),
  primary key (day, event_name, event_label, path, referrer_host, country_code, region, city, device_type, browser, os)
);

alter table public.analytics_rollups enable row level security;
revoke all on table public.analytics_rollups from public, anon, authenticated;
grant select on table public.analytics_rollups to authenticated;

drop policy if exists analytics_rollups_admin_read on public.analytics_rollups;
create policy analytics_rollups_admin_read on public.analytics_rollups
for select to authenticated
using ((select private.is_admin((select auth.uid()))));

create or replace function private.rollup_and_prune_analytics()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.analytics_rollups (
    day, event_name, event_label, path, referrer_host, country_code, region, city,
    device_type, browser, os, event_count, visitor_count, session_count, suspected_bot_count
  )
  select occurred_at::date, event_name, left(coalesce(metadata->>'result', ''), 64), path,
         coalesce(referrer_host, ''), coalesce(country_code, ''), coalesce(region, ''), coalesce(city, ''),
         device_type, browser, os, count(*), count(distinct visitor_id), count(distinct session_id),
         count(*) filter (where suspected_bot)
  from public.edge_events
  where occurred_at < current_date - 30
  group by 1,2,3,4,5,6,7,8,9,10,11
  on conflict (day, event_name, event_label, path, referrer_host, country_code, region, city, device_type, browser, os)
  do update set
    event_count = excluded.event_count,
    visitor_count = excluded.visitor_count,
    session_count = excluded.session_count,
    suspected_bot_count = excluded.suspected_bot_count;

  delete from public.edge_events where occurred_at < current_date - 30;
  delete from public.guestbook_submission_log where created_at < now() - interval '24 hours';

  update public.login_events set ip_address = null, user_agent = null
  where created_at < now() - interval '7 days' and (ip_address is not null or user_agent is not null);
  update public.security_events set ip_address = null
  where created_at < now() - interval '7 days' and ip_address is not null;
  update public.user_sessions set ip_address = null, user_agent = null
  where last_seen_at < now() - interval '7 days' and (ip_address is not null or user_agent is not null);
  update public.admin_audit_logs set ip_address = null
  where created_at < now() - interval '7 days' and ip_address is not null;
  update public.profiles set registration_ip = null
  where created_at < now() - interval '7 days' and registration_ip is not null;

  delete from cron.job_run_details where end_time < now() - interval '30 days';
end;
$$;

revoke execute on function private.rollup_and_prune_analytics() from public, anon, authenticated;

do $$
declare v_jobid bigint;
begin
  select jobid into v_jobid from cron.job where jobname = 'palve-analytics-retention';
  if v_jobid is not null then perform cron.unschedule(v_jobid); end if;
  perform cron.schedule('palve-analytics-retention', '15 19 * * *', 'select private.rollup_and_prune_analytics()');
end;
$$;

create or replace view public.admin_analytics_daily
with (security_invoker = true)
as
with combined as (
  select occurred_at::date as day,
         count(*) filter (where event_name = 'page_view')::bigint as page_views,
         count(distinct visitor_id)::bigint as visitors,
         count(distinct session_id)::bigint as sessions,
         count(*) filter (where event_name = 'gallery_gate_attempt')::bigint as gallery_attempts,
         count(*) filter (where event_name = 'gallery_gate_attempt' and metadata->>'result' = 'success')::bigint as gallery_successes,
         count(*) filter (where suspected_bot)::bigint as suspected_bots
  from public.edge_events group by 1
  union all
  select day,
         sum(event_count) filter (where event_name = 'page_view'),
         sum(visitor_count), sum(session_count),
         sum(event_count) filter (where event_name = 'gallery_gate_attempt'),
         sum(event_count) filter (where event_name = 'gallery_gate_attempt' and event_label = 'success'),
         sum(suspected_bot_count)
  from public.analytics_rollups group by day
)
select day, coalesce(sum(page_views),0)::bigint page_views,
       coalesce(sum(visitors),0)::bigint visitors,
       coalesce(sum(sessions),0)::bigint sessions,
       coalesce(sum(gallery_attempts),0)::bigint gallery_attempts,
       coalesce(sum(gallery_successes),0)::bigint gallery_successes,
       coalesce(sum(suspected_bots),0)::bigint suspected_bots
from combined group by day;

create or replace view public.admin_page_activity
with (security_invoker = true)
as
with combined as (
  select path, count(*)::bigint page_views, count(distinct visitor_id)::bigint visitors,
         count(distinct session_id)::bigint sessions, max(occurred_at) last_seen_at
  from public.edge_events where event_name = 'page_view' group by path
  union all
  select path, sum(event_count), sum(visitor_count), sum(session_count), max(day)::timestamptz
  from public.analytics_rollups where event_name = 'page_view' group by path
)
select path, sum(page_views)::bigint page_views, sum(visitors)::bigint visitors,
       sum(sessions)::bigint sessions, max(last_seen_at) last_seen_at
from combined group by path;

create or replace view public.admin_geo_activity
with (security_invoker = true)
as
with combined as (
  select coalesce(country_code,'') country_code, coalesce(region,'') region, coalesce(city,'') city,
         count(*)::bigint events, count(distinct visitor_id)::bigint visitors
  from public.edge_events group by 1,2,3
  union all
  select country_code, region, city, sum(event_count), sum(visitor_count)
  from public.analytics_rollups group by 1,2,3
)
select country_code, region, city, sum(events)::bigint events, sum(visitors)::bigint visitors
from combined group by 1,2,3;

create or replace view public.admin_device_activity
with (security_invoker = true)
as
with combined as (
  select device_type, browser, os, count(*)::bigint events, count(distinct visitor_id)::bigint visitors
  from public.edge_events group by 1,2,3
  union all
  select device_type, browser, os, sum(event_count), sum(visitor_count)
  from public.analytics_rollups group by 1,2,3
)
select device_type, browser, os, sum(events)::bigint events, sum(visitors)::bigint visitors
from combined group by 1,2,3;

create or replace view public.admin_referrer_activity
with (security_invoker = true)
as
with combined as (
  select coalesce(referrer_host,'') referrer_host, count(*)::bigint events,
         count(distinct visitor_id)::bigint visitors
  from public.edge_events group by 1
  union all
  select referrer_host, sum(event_count), sum(visitor_count)
  from public.analytics_rollups group by 1
)
select referrer_host, sum(events)::bigint events, sum(visitors)::bigint visitors
from combined group by 1;

create or replace view public.admin_suspicious_activity
with (security_invoker = true)
as
select left(ip_hash, 10) || '…' as fingerprint,
       max(country_code) country_code, max(region) region, max(city) city,
       count(*)::bigint request_count, count(*) filter (where suspected_bot)::bigint bot_events,
       min(occurred_at) first_seen_at, max(occurred_at) last_seen_at
from public.edge_events
where occurred_at > now() - interval '24 hours' and ip_hash is not null
group by ip_hash
having count(*) >= 100 or bool_or(suspected_bot);

revoke all on public.admin_analytics_daily, public.admin_page_activity, public.admin_geo_activity,
  public.admin_device_activity, public.admin_referrer_activity, public.admin_suspicious_activity
from public, anon;
grant select on public.admin_analytics_daily, public.admin_page_activity, public.admin_geo_activity,
  public.admin_device_activity, public.admin_referrer_activity, public.admin_suspicious_activity
to authenticated;

-- The service role is used only inside the signed Edge Function.
grant insert on table public.edge_events to service_role;
grant usage, select on sequence public.edge_events_id_seq to service_role;
